"""empty message

Revision ID: 32f182588e21
Revises: 0719fc82dd1e
Create Date: 2021-07-07 07:23:17.133506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f182588e21'
down_revision = '0719fc82dd1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(), nullable=True))
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genres')
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###
